version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fiscus
      POSTGRES_PASSWORD: fiscus
      POSTGRES_DB: fiscus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2024-01-01T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
  clamav:
    image: clamav/clamav:stable
    ports:
      - "3310:3310"
  api:
    build:
      context: .
    command: uvicorn apps.api.app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql+psycopg2://fiscus:fiscus@db:5432/fiscus
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: uploads
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_REGION: us-east-1
      S3_USE_PATH_STYLE: "1"
      CLAMD_HOST: clamav
      CLAMD_PORT: "3310"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - clamav
volumes:
  pgdata:
  minio:
