name: Web CI

on:
  push:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-ci.yml'

jobs:
  web-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/web
        run: |
          npm ci || npm install

      - name: Build
        working-directory: apps/web
        run: npm run build

      - name: Start server
        working-directory: apps/web
        run: |
          nohup npm start &
          npx wait-on http://localhost:3000

      - name: Playwright a11y smoke
        working-directory: apps/web
        run: |
          npx playwright@1.46.0 install --with-deps
          npx playwright@1.46.0 test tests/a11y.spec.ts

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: 'http://localhost:3000/'
          configPath: ./apps/web/lighthouserc.json
          uploadArtifacts: true

- name: k6 smoke
  uses: grafana/k6-action@v0.3.1
  with:
    filename: ./perf/smoke.js
  env:
    API_URL: http://localhost:3000
